controller_list:
  - name: fake_arm_controller
    joints:
      - ur_arm_shoulder_pan_joint
      - ur_arm_shoulder_lift_joint
      - ur_arm_elbow_joint
      - ur_arm_wrist_1_joint
      - ur_arm_wrist_2_joint
      - ur_arm_wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: flat