# Cam 0 Config
- distance: 0.3
  ypr: [90, 40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null
# Cam 1 Config
- distance: 0.3
  ypr: [225, 40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null
# Cam 2 Config
- distance: 0.3
  ypr: [315, 40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null
# Cam 3 Config
- distance: 0.3
  ypr: [90, -40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null
# Cam 4 Config
- distance: 0.3
  ypr: [225, -40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null
# Cam 5 Config
- distance: 0.3
  ypr: [315, -40, 0]
  W: 640
  H: 480
  up: [0., 0., 1.]
  up_axis_idx: 2
  near: 0.01
  far : 100.
  fov : 60. 
  target_pos: null